- name: Create a directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: /opt/mysql
    state: directory
    group: adm
    mode: '0775'
- name: copy definitions
  copy: src=./ dest=/opt/mysql/ group=adm mode=664
- name: write .env
  template:
    src: docker-compose.env
    dest: /opt/mysql/.env
- name: up
  become: true
  shell:
    chdir: /opt/mysql
    cmd: 'docker compose up -d'
- name: Pause for 2 minutes to init database
  ansible.builtin.pause:
    minutes: 2