- name: Create a directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: '{{ centrifugo_path }}'
    state: directory
    group: adm
    mode: '0775'
- name: copy compose
  copy: src=./ dest={{ centrifugo_path }}/ group=adm mode=664
- name: write config
  template:
    src: config.json
    dest: '{{ centrifugo_path }}/'
- name: up
  become: true
  shell:
    chdir: '{{ centrifugo_path }}'
    cmd: 'docker compose up -d'
